### ISSUE TITLE
[Request] Genshin Impact

### ISSUE THREAD

**Issue by HaruNashii** [Open-Wine-Components/umu-protonfixes#424]
I'm not sure if it's here that i should ask for it, or if genshin is already running but i don't know how, but yeah, i really don't know how to do it :(, sorry

**Is your feature request related to a problem? Please describe.**
My HoyoPlay Launcher Works Ok, but the Genshin Impact Doesn't launch, tried with umuproton, and proton-GE, with all genshin umu-id and with opengl flag

**Describe the solution you'd like**
i would like that the game opens without any issue, just like it happens when i add it as an non-steam game on steam

**Additional context**
when i tried putting the HoyoPlay launcher in the steam as as non-steam game, it works without any issue with, proton-experimental and proton-ge

**Comment by HaruNashii** [comment]
just tried to put the exactly same binary in the steam as an non-steam game and run with proton-GE and it just opened perfectly, it not even installed nothing new, it just worked

both the launcher and the game binary alone

**Comment by GloriousEggroll** [comment]
this isn't an issue with protonfixes. there actually isn't any protonfix for umu-genshin even though an ID is assigned, so protonfixes itself isn't applying any changes to the game.

I have verified the game is not launching in lutris either using the hoyo launcher. will report back.

**Comment by HaruNashii** [comment]
oh i see, i tried applying the [umu-genshin protonfix](https://github.com/Open-Wine-Components/umu-protonfixes/blob/9097d50ff45ccdf0291fbe7e39dbec0ac42f3684/gamefixes-umu/umu-genshin.py) that you commited, but it still doesn't launch the game

### my steps:
1. install the latest [Proton-GE](https://github.com/GloriousEggroll/proton-ge-custom) version (GE-Proton10-24)
2. install the latest version of HoyoPlay using the oficial link
3. download the [umu-genshin protonfix](https://github.com/Open-Wine-Components/umu-protonfixes/blob/9097d50ff45ccdf0291fbe7e39dbec0ac42f3684/gamefixes-umu/umu-genshin.py) that you commited
4. run "umu-run winetricks corefonts vcrun2019 dxvk" (idk why i do that but yea, i don't understand much things about proton and umu, i already tried without it and it give the same result)
5. complete launcher installation with umu-run
6. open the launcher with umu-run --config "path/to/my/config.toml"

### others:
<details> <summary>My UMU config file</summary>

```toml
[umu]
prefix = "~/.config/hoyoplay-umu/wine_prefix"
proton = "~/.config/hoyoplay-umu/Proton-GE_Latest"
title = "Genshin Impact"
store =	"none"
game_id = "umu-genshin"
codename = "none"
exe = "~/.config/hoyoplay-umu/wine_prefix/drive_c/Program Files/HoYoPlay/launcher.exe"

[env]
PROTON_VERB = "waitforexitandrun"
```
</details>

### i certified that:
- "~/.config/hoyoplay-umu/wine_prefix" exist and have all needed files
- "~/.config/hoyoplay-umu/Proton-GE_Latest" exist and have all needed files
- "~/.config/hoyoplay-umu/wine_prefix/drive_c/Program Files/HoYoPlay/launcher.exe" (the launcher binary) exist 
- "~/.config/hoyoplay-umu/wine_prefix/drive_c/Program Files/HoYoPlay/games/Genshin Impact game/GenshinImpact.exe" (the game binary) exist 
- "~/.config/protonfixes" exist and have all needed files
- the game works when running via steam as an non-steam game
- the launcher works when running via steam as an non-steam game
- umu-run is applying the localfixes
- umu-run is using the proton-ge version that i assigned to him
- no error log appeared while running umu-run --config "path/to/my/config.toml"

**Comment by HaruNashii** [comment]
> That protonfix needs to be supported on the proton side too. Wait for the next release of Proton-GE

oh i see, thank you so much, i will wait :)

**Comment by GloriousEggroll** [comment]
resolved in GE-Proton10-25

**Comment by DioEgizio** [comment]
the current protonfix doesn't fix genshin in egs so I opened a PR to fix it: https://github.com/Open-Wine-Components/umu-protonfixes/pull/425
